// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7ikB3iamWpe9w-CeUxbOiEimmgv6l2Vk',
    appId: '1:507347279480:web:3028bd807802091f81d78d',
    messagingSenderId: '507347279480',
    projectId: 'instagram-clone-dbde3',
    authDomain: 'instagram-clone-dbde3.firebaseapp.com',
    storageBucket: 'instagram-clone-dbde3.appspot.com',
    measurementId: 'G-DBVKBT2FE4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdxjtIwlYCHqyii8Khpb3r1S9Fcoog5pE',
    appId: '1:507347279480:android:f7a05bf9fd8dada581d78d',
    messagingSenderId: '507347279480',
    projectId: 'instagram-clone-dbde3',
    storageBucket: 'instagram-clone-dbde3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLQMbWizYdNUh-nYSjRoSnI_K7QKyQSC4',
    appId: '1:507347279480:ios:16f7acffc01b752381d78d',
    messagingSenderId: '507347279480',
    projectId: 'instagram-clone-dbde3',
    storageBucket: 'instagram-clone-dbde3.appspot.com',
    iosClientId: '507347279480-cqf204i9eabcckhe37l3gp73frenseu3.apps.googleusercontent.com',
    iosBundleId: 'com.hady.dev.instagramclone.instagramClone',
  );
}
